'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'..'),routes=['about','privacy','contact'];
const pages=Object.fromEntries(routes.map(route=>[route,fs.readFileSync(path.join(root,route,'index.html'),'utf8')]));
function tagContent(html,pattern){return html.match(pattern)?.[1]||''}
function analyticsCount(html){return(html.match(/<script\s+defer\s+src="\/_vercel\/insights\/script\.js"><\/script>/g)||[]).length}

test('About, Privacy, and Contact static route files exist',()=>{for(const route of routes)assert.equal(fs.existsSync(path.join(root,route,'index.html')),true,`missing /${route}/`);assert.equal(fs.existsSync(path.join(root,'assets','info-pages.css')),true)});

test('information pages have unique titles, descriptions, canonicals, and Open Graph metadata',()=>{const titles=[],descriptions=[];for(const route of routes){const html=pages[route],title=tagContent(html,/<title>([^<]+)<\/title>/i),description=tagContent(html,/<meta\s+name="description"\s+content="([^"]+)">/i),canonical=tagContent(html,/<link\s+rel="canonical"\s+href="([^"]+)">/i),ogTitle=tagContent(html,/<meta\s+property="og:title"\s+content="([^"]+)">/i),ogDescription=tagContent(html,/<meta\s+property="og:description"\s+content="([^"]+)">/i),ogUrl=tagContent(html,/<meta\s+property="og:url"\s+content="([^"]+)">/i);assert.ok(title);assert.ok(description);assert.equal(canonical,`https://www.spinorder.com/${route}/`);assert.equal(ogTitle,title);assert.equal(ogDescription,description);assert.equal(ogUrl,canonical);assert.match(html,/<meta property="og:site_name" content="SpinOrder">/);assert.match(html,/<meta property="og:type" content="website">/);titles.push(title);descriptions.push(description)}assert.equal(new Set(titles).size,3);assert.equal(new Set(descriptions).size,3)});

test('each information page has one meaningful H1 and semantic navigation',()=>{for(const route of routes){const html=pages[route],headings=[...html.matchAll(/<h1\b[^>]*>(.*?)<\/h1>/gis)];assert.equal(headings.length,1,`/${route}/ must have one H1`);assert.ok(headings[0][1].replace(/<[^>]+>/g,'').trim().length>3);assert.match(html,/<header class="site-header">/);assert.match(html,/<main class="info-main">/);assert.match(html,/<footer class="info-footer">/);assert.match(html,/href="\/" aria-label="SpinOrder home"/)} });

test('each information page includes Vercel Analytics exactly once with defer',()=>{for(const route of routes)assert.equal(analyticsCount(pages[route]),1,`/${route}/ analytics count`)});

test('homepage footer links to every information page accessibly',()=>{const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),footer=tagContent(html,/<footer class="publisher-footer">([\s\S]*?)<\/footer>/i);assert.match(footer,/<nav aria-label="Footer">/);for(const route of routes)assert.match(footer,new RegExp(`href="/${route}/"`))});

test('Contact publishes only the support mailto action and no form',()=>{const html=pages.contact,addresses=html.match(/[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}/gi)||[];assert.match(html,/href="mailto:support@spinorder\.com\?subject=SpinOrder%20Support"/);assert.match(html,/>Email support@spinorder\.com<\/a>/);assert.doesNotMatch(html,/<form\b/i);assert.deepEqual([...new Set(addresses.map(value=>value.toLowerCase()))],['support@spinorder.com'])});

test('Privacy page documents only audited storage, sharing, hosting, analytics, and support email behavior',()=>{const html=pages.privacy;assert.match(html,/Last updated: August 28, 2026\./);assert.match(html,/session storage/);assert.match(html,/local storage/);assert.match(html,/Imported text or CSV file contents are read locally/);assert.match(html,/does not automatically upload participant names or results/);assert.match(html,/hosted by Vercel/);assert.match(html,/anonymized, aggregated traffic analytics/);assert.match(html,/without third-party cookies/);assert.match(html,/through Zoho Mail/);assert.match(html,/support@spinorder\.com/);assert.match(html,/https:\/\/vercel\.com\/docs\/analytics\/privacy-policy/);assert.match(html,/https:\/\/vercel\.com\/legal\/privacy-notice/);assert.doesNotMatch(html,/sell(?:s|ing)? personal|certified|guarantee|legal advice|retain(?:ed|s)? for \d+/i)});

test('service worker precaches public routes and their shared stylesheet',()=>{const worker=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');assert.match(worker,/spinorder-draft-v40/);for(const route of routes)assert.match(worker,new RegExp(`'\\./${route}/'`));assert.match(worker,/'\.\/assets\/info-pages\.css'/)});

test('sitemap lists the canonical homepage and all information routes',()=>{const sitemap=fs.readFileSync(path.join(root,'sitemap.xml'),'utf8'),locations=[...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map(match=>match[1]);assert.deepEqual(locations,['https://www.spinorder.com/','https://www.spinorder.com/about/','https://www.spinorder.com/privacy/','https://www.spinorder.com/contact/']);assert.doesNotMatch(sitemap,/#/)});
