'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const participants=require('../participant-state.js');
const names=count=>Array.from({length:count},(_,index)=>`Name ${index+1}`);

test('manual lists allow 20 names and reject the 21st',()=>{const twenty=names(20);assert.equal(participants.validateList(twenty,true,participants.MANUAL_MAX_NAMES).valid,true);assert.equal(participants.add(twenty,'Another',participants.MANUAL_MAX_NAMES).valid,false)});
test('adds, edits, removes, trims, and validates names',()=>{const added=participants.add([],' Alice ');assert.deepEqual(added.names,['Alice']);assert.deepEqual(participants.edit(added.names,0,' Alicia ').names,['Alicia']);assert.deepEqual(participants.remove(['Alicia','Bob'],0),['Bob']);assert.equal(participants.add([],' ').valid,false);assert.equal(participants.add([],'x'.repeat(51)).valid,false);assert.equal(participants.add(['Alice'],'alice').valid,false)});
test('loads Team 1 through Team 12 as a manual example',()=>{const result=participants.exampleNames();assert.equal(result.length,12);assert.equal(result[0],'Team 1');assert.equal(result[11],'Team 12')});
test('parses comma-separated and newline-separated TXT input',()=>{assert.deepEqual(participants.importNames('names.txt',20,'Alice,Bob,Carol').names,['Alice','Bob','Carol']);assert.deepEqual(participants.importNames('names.txt',20,'Alice\nBob\nCarol').names,['Alice','Bob','Carol'])});
test('parses quoted CSV values and optional headers',()=>{assert.deepEqual(participants.importNames('names.csv',30,'Name\n"Smith, Alex"\nTaylor').names,['Smith, Alex','Taylor']);assert.deepEqual(participants.importNames('names.csv',30,'Team,Alex,Bob').names,['Alex','Bob'])});
test('imports 21, 25, and 60 names and rejects 61 without mutating a valid list',()=>{for(const count of [21,25,60])assert.equal(participants.importNames('names.csv',100,names(count).join(',')).names.length,count);const current=names(25),rejected=participants.importNames('names.csv',200,names(61).join(','));assert.equal(rejected.valid,false);assert.equal(current.length,25)});
test('rejects unsupported and oversized files',()=>{assert.equal(participants.importNames('names.pdf',20,'A,B').valid,false);assert.equal(participants.importNames('names.csv',102401,'A,B').valid,false)});
test('returns only a safe base filename in import summaries',()=>{const result=participants.importNames('C:\\fakepath\\golf-groups.csv',50,'Alice,Bob');assert.equal(result.filename,'golf-groups.csv');assert.equal(result.summary,'2 names imported from golf-groups.csv')});
test('restores imported mode and filename without file contents',()=>{const data=new Map(),storage={setItem:(key,value)=>data.set(key,value),getItem:key=>data.get(key)??null};const state={names:['Alice','Bob'],mode:'import',filename:'people.csv'};assert.equal(participants.save(storage,state),true);assert.deepEqual(participants.load(storage),state);assert.doesNotMatch(data.get(participants.STORAGE_KEY),/file contents/);data.set(participants.STORAGE_KEY,'{bad');assert.deepEqual(participants.load(storage),{names:[],mode:'manual',filename:''})});
test('produces sorted results and both reveal directions for 2, 12, and 60 names',()=>{for(const count of [2,12,60]){assert.deepEqual(participants.positions(count),Array.from({length:count},(_,index)=>index+1));assert.deepEqual(participants.revealPositions(count,'first'),Array.from({length:count},(_,index)=>index+1));assert.deepEqual(participants.revealPositions(count,'last'),Array.from({length:count},(_,index)=>count-index));assert.equal(participants.wheelEntries(names(count),['red','blue']).length,count)}});
test('picker and drag-and-drop share importParticipantFile and prevent default browser drops',()=>{const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');assert.match(html,/<label class="secondary-action" id="chooseFile" for="nameFile"/);assert.match(html,/<label class="drop-zone" id="dropZone" for="nameFile"/);assert.match(html,/nameFile\.addEventListener\('change'.*importParticipantFile/s);assert.match(html,/dropZone\.addEventListener\('drop'.*importParticipantFile/s);assert.match(html,/document\.addEventListener\('drop',event=>event\.preventDefault\(\)\)/)});
test('participant listener initialization registers valid callbacks and both import paths handle 60 names',async()=>{
  const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
  const literalRegistrations=[...html.matchAll(/\.addEventListener\(\s*(['"])[^'"]+\1\s*,\s*/g)],loopRegistrations=[...html.matchAll(/\.addEventListener\(\s*eventName\s*,\s*/g)];
  assert.equal(literalRegistrations.length+loopRegistrations.length,(html.match(/\.addEventListener\(/g)||[]).length,'every addEventListener call must include an event type and callback');
  assert.equal(loopRegistrations.length,2,'both drag-state loops should register their eventName with a callback');
  const body=html.match(/function registerParticipantListeners\(\)\{([\s\S]*?)\r?\n\}\r?\nregisterParticipantListeners\(\);/);
  assert.ok(body,'participant listener initializer must run during startup');
  class Target{constructor(){this.listeners=new Map();this.classList={toggle(){},remove(){}};this.files=[];this.value='';this.click=()=>{}}addEventListener(...args){assert.equal(args.length,2);assert.equal(typeof args[0],'string');assert.equal(typeof args[1],'function');this.listeners.set(args[0],args[1])}}
  const addNameButton=new Target(),nameInput=new Target(),exampleNamesButton=new Target(),clearNamesButton=new Target(),chooseFile=new Target(),dropZone=new Target(),nameFile=new Target(),participantsForm=new Target(),document=new Target();
  const summaries=[];const importParticipantFile=async file=>{const result=participants.importNames(file.name,file.size,await file.text());summaries.push(result.summary);return result};
  const initialize=new Function('addNameButton','nameInput','exampleNamesButton','clearNamesButton','chooseFile','dropZone','nameFile','participantsForm','document','addParticipant','importParticipantFile',body[1]);
  assert.doesNotThrow(()=>initialize(addNameButton,nameInput,exampleNamesButton,clearNamesButton,chooseFile,dropZone,nameFile,participantsForm,document,()=>{},importParticipantFile));
  for(const [target,types] of [[addNameButton,['click']],[nameInput,['keydown']],[exampleNamesButton,['click']],[clearNamesButton,['click']],[chooseFile,['keydown']],[dropZone,['keydown','dragenter','dragover','dragleave','dragend','drop']],[nameFile,['change']],[participantsForm,['submit']]])for(const type of types)assert.equal(typeof target.listeners.get(type),'function',`${type} listener should be registered`);
  const file={name:'spinorder-test-60-names.csv',size:600,text:async()=>names(60).join(',')};
  nameFile.files=[file];nameFile.listeners.get('change')();
  dropZone.listeners.get('drop')({preventDefault(){},dataTransfer:{files:[file]}});
  await new Promise(resolve=>setImmediate(resolve));
  assert.deepEqual(summaries,['60 names imported from spinorder-test-60-names.csv','60 names imported from spinorder-test-60-names.csv']);
});
test('filename clears for examples and clear-all, and count follows list mode',()=>{const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');assert.match(html,/exampleNamesButton.*participantMode='manual';importedFilename=''/s);assert.match(html,/participantNames=\[\];participantMode='manual';importedFilename=''/);assert.match(html,/function participantLimit\(\)/)});
test('navigation, safe rendering, and result reset are wired',()=>{const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');assert.match(html,/id="participantsView"/);assert.match(html,/id="editNames"/);assert.match(html,/team\.textContent/);assert.match(html,/function initializeRandomizer\(names\).*picks=\{\}.*hasCompletedSpin=false/s)});
test('editing locks after a spin and reset restores availability',()=>{const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');assert.match(html,/hasCompletedSpin=true.*syncEditingAvailability\(\)/s);assert.match(html,/editNames\.hidden=hasCompletedSpin/);assert.match(html,/revealOrder.*disabled=hasCompletedSpin/);assert.match(html,/initializeRandomizer\(names\).*hasCompletedSpin=false/s);assert.match(html,/id="editSetup"/)});
