'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
function attribute(tag,name){const match=tag.match(new RegExp(`${name}=["']([^"']+)["']`,'i'));return match&&match[1]}
function meta(selector,value){const tags=[...html.matchAll(/<meta\s+[^>]*>/gi)].map(match=>match[0]);return tags.find(tag=>attribute(tag,selector)===value)}

test('homepage title and description are concise and search-ready',()=>{const title=html.match(/<title>([^<]+)<\/title>/i)?.[1],descriptionTag=meta('name','description'),description=attribute(descriptionTag||'','content');assert.equal(title,'Free Randomizer for Drafts, Teams &amp; More | SpinOrder');assert.ok(title.includes('Free Randomizer'));assert.ok(title.includes('SpinOrder'));assert.ok(description.length>=140&&description.length<=160,`description length was ${description.length}`);assert.match(description,/free, no-login randomizer/i)});

test('canonical, robots, language, and theme metadata are valid',()=>{assert.match(html,/<html\s+lang="en">/i);assert.match(html,/<link\s+rel="canonical"\s+href="https:\/\/www\.spinorder\.com\/">/i);assert.equal(attribute(meta('name','robots'),'content'),'index, follow');assert.equal(attribute(meta('name','theme-color'),'content'),'#07110b')});

test('Open Graph and Twitter metadata describe the canonical homepage',()=>{for(const [property,value] of [['og:title','Free Randomizer for Drafts, Teams &amp; More | SpinOrder'],['og:url','https://www.spinorder.com/'],['og:site_name','SpinOrder'],['og:type','website'],['og:image','https://www.spinorder.com/social-preview.png']])assert.equal(attribute(meta('property',property),'content'),value);assert.ok(attribute(meta('property','og:description'),'content').length>=140);assert.equal(attribute(meta('name','twitter:card'),'content'),'summary');assert.equal(attribute(meta('name','twitter:title'),'content'),'Free Randomizer for Drafts, Teams &amp; More | SpinOrder');assert.ok(attribute(meta('name','twitter:description'),'content').length>=140);assert.equal(attribute(meta('name','twitter:image'),'content'),'https://www.spinorder.com/social-preview.png')});

test('WebApplication JSON-LD is factual and valid JSON',()=>{const source=html.match(/<script\s+type="application\/ld\+json">([\s\S]*?)<\/script>/i)?.[1];assert.ok(source);const value=JSON.parse(source);assert.equal(value['@context'],'https://schema.org');assert.equal(value['@type'],'WebApplication');assert.equal(value.name,'SpinOrder');assert.equal(value.url,'https://www.spinorder.com/');assert.equal(value.applicationCategory,'UtilitiesApplication');assert.equal(value.operatingSystem,'Any');assert.equal(value.isAccessibleForFree,true);assert.deepEqual(value.offers,{'@type':'Offer',price:'0',priceCurrency:'USD'});for(const unsupported of ['aggregateRating','review','downloadCount'])assert.equal(value[unsupported],undefined)});

test('splash view contains one meaningful H1 and concise visible use-case copy',()=>{const splash=html.slice(html.indexOf('<section id="landingView"'),html.indexOf('<section id="setupView"')),headings=[...splash.matchAll(/<h1\b[^>]*>(.*?)<\/h1>/gis)];assert.equal(headings.length,1);assert.match(headings[0][1],/Make the order\. Make it fair\./);assert.match(splash,/class="landing-intro"[^>]*>Use this free randomizer/i);assert.match(splash,/fantasy football drafts, golf groups, team assignments, classroom activities, generic drawings/i)});

test('robots.txt allows crawling and references the canonical sitemap',()=>{const robots=fs.readFileSync(path.join(root,'robots.txt'),'utf8');assert.match(robots,/^User-agent: \*$/m);assert.match(robots,/^Allow: \/$/m);assert.match(robots,/^Sitemap: https:\/\/www\.spinorder\.com\/sitemap\.xml$/m);assert.doesNotMatch(robots,/Disallow:\s*\//)});

test('sitemap contains canonical public routes and no hash routes',()=>{const sitemap=fs.readFileSync(path.join(root,'sitemap.xml'),'utf8'),locations=[...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map(match=>match[1]);assert.match(sitemap,/^<\?xml version="1\.0" encoding="UTF-8"\?>/);assert.match(sitemap,/<urlset xmlns="http:\/\/www\.sitemaps\.org\/schemas\/sitemap\/0\.9">/);assert.deepEqual(locations,['https://www.spinorder.com/','https://www.spinorder.com/about/','https://www.spinorder.com/privacy/','https://www.spinorder.com/contact/','https://www.spinorder.com/fantasy-football-draft-order-randomizer/','https://www.spinorder.com/random-team-generator/']);assert.doesNotMatch(sitemap,/#/)});

test('SEO runtime files are included in the versioned offline cache',()=>{const worker=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');assert.match(worker,/spinorder-draft-v44/);assert.match(worker,/'\.\/robots\.txt'/);assert.match(worker,/'\.\/sitemap\.xml'/);assert.match(worker,/'\.\/social-preview\.png'/)});
