'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const teams=require('../team-assignment.js'),setup=require('../setup-state.js'),exportsApi=require('../results-export.js');
const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
function sequence(values){let index=0;return()=>values[index++%values.length]}
function roundRobinAssignments(names,teamCount,nextUint32){const remaining=[...names],assignments=[];while(remaining.length){const selectedIndex=teams.randomIndex(remaining.length,nextUint32),name=remaining.splice(selectedIndex,1)[0];assignments.push({name,team:teams.teamForCompleted(assignments.length,teamCount)})}return assignments}

test('rejection sampling discards values outside the largest unbiased range',()=>{const source=sequence([0xffffffff,7]);assert.equal(teams.randomIndex(10,source),7)});
test('destinations rotate deterministically from Team 1 through Team N',()=>{assert.deepEqual(Array.from({length:8},(_,completed)=>teams.teamForCompleted(completed,3)),[1,2,3,1,2,3,1,2]);assert.throws(()=>teams.teamForCompleted(-1,3));assert.throws(()=>teams.teamForCompleted(0,1))});
test('odd participant totals put round-robin extras on the first teams',()=>{const assigned=roundRobinAssignments(['A','B','C','D','E','F','G'],3,sequence([6,1,3,0,2]));assert.deepEqual(teams.grouped(assigned,3).map(group=>group.members.length),[3,2,2]);assert.equal(new Set(assigned.map(item=>item.name)).size,7)});
test('even participant totals stay equal and every participant appears once',()=>{const names=Array.from({length:12},(_,index)=>`Person ${index+1}`),assigned=roundRobinAssignments(names,4,sequence([3,7,11,19,23,29]));assert.deepEqual(teams.grouped(assigned,4).map(group=>group.members.length),[3,3,3,3]);assert.deepEqual([...assigned.map(item=>item.name)].sort(),[...names].sort())});
test('team count validates participant-aware minimum and maximum',()=>{assert.equal(teams.validateTeamCount(2,2).valid,true);assert.equal(teams.validateTeamCount(1,5).valid,false);assert.equal(teams.validateTeamCount(6,5).valid,false);assert.equal(teams.validateTeamCount(11,20).valid,false);assert.equal(teams.validateTeamCount('2.5',6).valid,false)});
test('team-generator preset applies Generic, Team Assignment, and two teams',()=>{assert.deepEqual(setup.valuesForPreset('team-generator'),{...setup.DEFAULT_VALUES,activity:'Generic',activityLabel:'Team Assignment',teamCount:2});assert.equal(setup.presetFromSearch('?preset=team-generator'),'team-generator');assert.equal(setup.presetFromSearch('?preset=team-generator-other'),null)});
test('preset application persists before URL cleanup and failed application is not consumed',()=>{const data=new Map(),storage={setItem:(key,value)=>data.set(key,value),getItem:key=>data.get(key)||null};const applied=setup.applyPreset(storage,'?preset=team-generator');assert.equal(applied.key,'team-generator');assert.deepEqual(setup.load(storage),applied.values);const blocked={setItem:()=>{throw new Error('blocked')},getItem:()=>null};assert.equal(setup.applyPreset(blocked,'?preset=team-generator'),null);assert.equal(setup.applyPreset(storage,'?preset=unknown'),null);assert.match(html,/if\(presetApplication\)history\.replaceState\(\{spinorderView:'setup'\},'',location\.pathname\+'#setup'\)/)});
test('refresh after preset cleanup restores user-entered session data',()=>{const data=new Map(),storage={setItem:(key,value)=>data.set(key,value),getItem:key=>data.get(key)||null};assert.ok(setup.applyPreset(storage,'?preset=team-generator'));const edited={...setup.DEFAULT_VALUES,eventName:'Saturday Groups',activity:'Generic',activityLabel:'Team Assignment',teamCount:4};assert.equal(setup.save(storage,edited),true);assert.deepEqual(setup.load(storage),edited);assert.equal(setup.presetFromSearch(''),null)});
test('runtime computes destination from completed count and randomly selects afterward',()=>{assert.match(html,/function currentDestinationTeam\(\)\{return isTeamMode\(\)\?SpinOrderTeams\.teamForCompleted\(positionState\.completed\.length,setupValues\.teamCount\):null\}/);assert.match(html,/const destinationTeam=currentDestinationTeam\(\),idx=rand\(remaining\.length\),selected=remaining\[idx\]/);assert.doesNotMatch(html,/teamPlan|SpinOrderTeams\.assign/);assert.match(html,/Current destination: \$\{words\.singular\}/);assert.match(html,/assigned to \$\{words\.singular\}/)});
test('manual and automatic spins share rotation while pause, resume, and stop cannot advance it',()=>{assert.equal((html.match(/function executeSpin\(/g)||[]).length,1);assert.match(html,/onSpinRequested:\(\)=>\{if\(!executeSpin\(true\)\)autoController\.stop\(\)\}/);assert.match(html,/else executeSpin\(false\)/);for(const action of ['pauseAuto','resumeAuto','stopAuto']){const handler=html.match(new RegExp(`${action}\\.addEventListener\\('click',([^;]+)`))?.[1]||'';assert.ok(handler);assert.doesNotMatch(handler,/teamForCompleted|completeSpin|completed\.length|picks/)}});
test('reset restarts at Team 1 and grouped sharing stays team-aware',()=>{assert.equal(teams.teamForCompleted(0,3),1);assert.match(html,/function resetDraft\(\)\{initializeRandomizer\(eventParticipants\)\}/);assert.match(html,/positionState=SpinOrderPositions\.create\(eventParticipants\.length,setupValues\.revealOrder\)/);const picks={1:{name:'A',team:1},2:{name:'B',team:2},3:{name:'C',team:1}},data=exportsApi.model({eventName:'Groups',activity:'Generic',orderType:'Team Assignment',completedAt:'2026-09-01T12:00:00Z',picks,total:3,teamCount:2});assert.deepEqual(data.groups.map(group=>group.members.map(item=>item.name)),[['A','C'],['B']]);assert.match(exportsApi.text(data),/Team 1\n- A\n- C\n\nTeam 2\n- B/);assert.match(decodeURIComponent(exportsApi.mailUrl('gmail',data).url),/Team 1\n- A/);assert.match(exportsApi.csv(data),/^\uFEFF"Team","Name"/)});
test('existing order exports remain unchanged',()=>{const order=exportsApi.model({eventName:'Order',completedAt:'2026-09-01T12:00:00Z',picks:{1:{name:'A'}},total:1});assert.match(exportsApi.text(order),/1\. A/);assert.doesNotMatch(exportsApi.text(order),/Team 1/)});
